spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zoo?useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admine
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    view:
      prefix: /
      suffix: .html

server:
  port: 9095
  servlet:
    context-path: /
